apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: besu-alerts
  namespace: monitoring
  labels:
    app: prometheus
    release: prometheus
spec:
  groups:
  - name: besu.rules
    rules:
    - alert: BesuNodeDown
      expr: up{job="besu-validators"} == 0
      for: 5m
      labels:
        severity: critical
        type: validator
      annotations:
        summary: "Besu node {{ $labels.pod }} is down"
        description: "Validator node {{ $labels.pod }} in region {{ $labels.region }} has been down for more than 5 minutes"

    - alert: BesuPeerCountLow
      expr: besu_network_peer_count < 3
      for: 5m
      labels:
        severity: warning
        type: network
      annotations:
        summary: "Low peer count on {{ $labels.pod }}"
        description: "Node {{ $labels.pod }} in region {{ $labels.region }} has less than 3 peers for more than 5 minutes"

    - alert: BesuBlockHeightStuck
      expr: rate(besu_blockchain_height[15m]) == 0
      for: 5m
      labels:
        severity: critical
        type: consensus
      annotations:
        summary: "Block height stuck on {{ $labels.pod }}"
        description: "Node {{ $labels.pod }} in region {{ $labels.region }} block height hasn't increased in 15 minutes"

    - alert: BesuHighMemoryUsage
      expr: process_resident_memory_bytes / process_virtual_memory_bytes > 0.8
      for: 15m
      labels:
        severity: warning
        type: resource
      annotations:
        summary: "High memory usage on {{ $labels.pod }}"
        description: "Node {{ $labels.pod }} in region {{ $labels.region }} memory usage is above 80% for 15 minutes"

    - alert: BesuHighCPUUsage
      expr: rate(process_cpu_seconds_total[5m]) > 0.9
      for: 15m
      labels:
        severity: warning
        type: resource
      annotations:
        summary: "High CPU usage on {{ $labels.pod }}"
        description: "Node {{ $labels.pod }} in region {{ $labels.region }} CPU usage is above 90% for 15 minutes"

    - alert: BesuSyncDelayed
      expr: besu_synchronizer_block_height - besu_blockchain_height > 50
      for: 10m
      labels:
        severity: warning
        type: sync
      annotations:
        summary: "Sync delayed on {{ $labels.pod }}"
        description: "Node {{ $labels.pod }} in region {{ $labels.region }} is more than 50 blocks behind the network"

    - alert: BesuNetworkPartition
      expr: count(count by (region) (up{job="besu-validators"} == 1)) < 2
      for: 5m
      labels:
        severity: critical
        type: network
      annotations:
        summary: "Network partition detected"
        description: "Less than 2 regions have active validators, possible network partition"

  - name: besu-network-alerts
    rules:
    # Mainnet Alerts (Chain ID: 138)
    - alert: MainnetNodeDown
      expr: up{chain_id="138"} == 0
      for: 2m
      labels:
        severity: critical
        network: mainnet
      annotations:
        summary: "Mainnet Node Down"
        description: "Node {{ $labels.instance }} has been down for more than 2 minutes"

    - alert: MainnetHighCPUUsage
      expr: rate(process_cpu_seconds_total{chain_id="138"}[5m]) * 100 > 85
      for: 10m
      labels:
        severity: warning
        network: mainnet
      annotations:
        summary: "High CPU Usage on Mainnet Node"
        description: "Node {{ $labels.instance }} CPU usage is above 85% for 10 minutes"

    - alert: MainnetLowPeerCount
      expr: besu_peers{chain_id="138"} < 10
      for: 5m
      labels:
        severity: warning
        network: mainnet
      annotations:
        summary: "Low Peer Count on Mainnet"
        description: "Node {{ $labels.instance }} has less than 10 peers"

    # Testnet Alerts (Chain ID: 2138)
    - alert: TestnetNodeDown
      expr: up{chain_id="2138"} == 0
      for: 5m
      labels:
        severity: warning
        network: testnet
      annotations:
        summary: "Testnet Node Down"
        description: "Node {{ $labels.instance }} has been down for more than 5 minutes"

    - alert: TestnetHighCPUUsage
      expr: rate(process_cpu_seconds_total{chain_id="2138"}[5m]) * 100 > 90
      for: 15m
      labels:
        severity: warning
        network: testnet
      annotations:
        summary: "High CPU Usage on Testnet Node"
        description: "Node {{ $labels.instance }} CPU usage is above 90% for 15 minutes"

    - alert: TestnetLowPeerCount
      expr: besu_peers{chain_id="2138"} < 5
      for: 10m
      labels:
        severity: warning
        network: testnet
      annotations:
        summary: "Low Peer Count on Testnet"
        description: "Node {{ $labels.instance }} has less than 5 peers"

    # Devnet Alerts (Chain ID: 1337)
    - alert: DevnetNodeDown
      expr: up{chain_id="1337"} == 0
      for: 10m
      labels:
        severity: info
        network: devnet
      annotations:
        summary: "Devnet Node Down"
        description: "Node {{ $labels.instance }} has been down for more than 10 minutes"

    - alert: DevnetHighCPUUsage
      expr: rate(process_cpu_seconds_total{chain_id="1337"}[5m]) * 100 > 95
      for: 30m
      labels:
        severity: info
        network: devnet
      annotations:
        summary: "High CPU Usage on Devnet Node"
        description: "Node {{ $labels.instance }} CPU usage is above 95% for 30 minutes"

    # Common Storage Alerts
    - alert: StorageNearingCapacity
      expr: |
        (
          kubelet_volume_stats_used_bytes{chain_id="138"}
          / kubelet_volume_stats_capacity_bytes{chain_id="138"}
          * 100 > 80
        )
        or
        (
          kubelet_volume_stats_used_bytes{chain_id="2138"}
          / kubelet_volume_stats_capacity_bytes{chain_id="2138"}
          * 100 > 85
        )
        or
        (
          kubelet_volume_stats_used_bytes{chain_id="1337"}
          / kubelet_volume_stats_capacity_bytes{chain_id="1337"}
          * 100 > 90
        )
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: "Storage Capacity Alert"
        description: "Volume {{ $labels.persistentvolumeclaim }} is nearing capacity threshold for its network type"

    # Network-Specific Block Sync Alerts
    - alert: MainnetBlockSyncDelay
      expr: increase(besu_blockchain_height{chain_id="138"}[1h]) < 10
      for: 10m
      labels:
        severity: critical
        network: mainnet
      annotations:
        summary: "Mainnet Block Sync Delay"
        description: "Node {{ $labels.instance }} block sync is delayed"

    - alert: TestnetBlockSyncDelay
      expr: increase(besu_blockchain_height{chain_id="2138"}[1h]) < 5
      for: 15m
      labels:
        severity: warning
        network: testnet
      annotations:
        summary: "Testnet Block Sync Delay"
        description: "Node {{ $labels.instance }} block sync is delayed"