apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: besu-validator-testnet
  namespace: besu
spec:
  serviceName: besu-validator-testnet
  replicas: 4
  selector:
    matchLabels:
      app: besu-validator
      network: testnet
  template:
    metadata:
      labels:
        app: besu-validator
        network: testnet
    spec:
      containers:
      - name: besu
        image: hyperledger/besu:latest
        resources:
          requests:
            cpu: "8"
            memory: "16Gi"
          limits:
            cpu: "8"
            memory: "16Gi"
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Gi
      storageClassName: standard-ssd