apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "besu-validator.fullname" . }}
  labels:
    {{- include "besu-validator.labels" . | nindent 4 }}
    network.besu.hyperledger.org/name: {{ .Values.networks.networkName }}
    network.besu.hyperledger.org/chainId: {{ .Values.networks.chainId | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "besu-validator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "besu-validator.selectorLabels" . | nindent 8 }}
        network.besu.hyperledger.org/name: {{ .Values.networks.networkName }}
        network.besu.hyperledger.org/chainId: {{ .Values.networks.chainId | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "besu-validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --network={{ .Values.networks.networkName | lower }}
            - --data-path=/data
            - --genesis-file=/opt/besu/genesis.json
            {{- if eq .Values.networks.chainId "138" }}
            # Mainnet specific args
            - --sync-mode=FULL
            - --pruning-enabled=true
            - --data-storage-format=BONSAI
            - --metrics-category=PEERS,PROCESS,BLOCKCHAIN,SYNCHRONIZER,NETWORK,PEERS,RPC
            {{- else if eq .Values.networks.chainId "2138" }}
            # Testnet specific args
            - --sync-mode=SNAP
            - --pruning-enabled=true
            - --metrics-category=PEERS,PROCESS,BLOCKCHAIN,SYNCHRONIZER
            {{- else }}
            # Devnet specific args
            - --sync-mode=SNAP
            - --pruning-enabled=false
            - --metrics-category=PEERS,PROCESS
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
          resources:
            {{- if eq .Values.networks.chainId "138" }}
            {{- toYaml .Values.networks.mainnet.validators.resources | nindent 12 }}
            {{- else if eq .Values.networks.chainId "2138" }}
            {{- toYaml .Values.networks.testnet.validators.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.networks.devnet.validators.resources | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: validator-keys
              mountPath: /opt/besu/keys
              readOnly: true
            - name: genesis
              mountPath: /opt/besu/genesis.json
              subPath: genesis.json
              readOnly: true
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "besu-validator.fullname" . }}-data
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}