{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "besu-validator.fullname" . }}
  labels:
    {{- include "besu-validator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "besu-validator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}