apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-validator.fullname" . }}
  labels:
    {{- include "besu-validator.labels" . | nindent 4 }}
    app.kubernetes.io/component: besu-network
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.network.p2pPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.network.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.network.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
    - port: {{ .Values.besu.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "besu-validator.selectorLabels" . | nindent 4 }}