global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'besu-nodes'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['besu']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        regex: besu.*
        action: keep
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
        target_label: role
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: instance
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
      - source_labels: [__meta_kubernetes_pod_label_region]
        target_label: region
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: besu_.*
        action: keep

  - job_name: 'besu-network'
    static_configs:
      - targets: ['localhost:9545']
    metrics_path: /metrics
    scheme: http
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: besu_network_.*
        action: keep

  - job_name: 'node-metrics'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_kubernetes_node_label_region]
        target_label: region

  - job_name: 'kube-state-metrics'
    kubernetes_sd_configs:
      - role: service
        namespaces:
          names: ['kube-system']
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        regex: kube-state-metrics
        action: keep
      - source_labels: [__meta_kubernetes_service_port_name]
        regex: http-metrics
        action: keep

  - job_name: 'besu-validators'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - besu
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: besu-validator
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        regex: 'true'
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_label_region]
        target_label: region
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
        action: replace

  - job_name: 'besu-bootnodes'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - besu
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: besu-bootnode
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        regex: 'true'
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_label_region]
        target_label: region
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
        action: replace

  - job_name: 'besu-rpc'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - besu
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: besu-rpc
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        regex: 'true'
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_label_region]
        target_label: region
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
        action: replace

  - job_name: 'besu-mainnet'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9545']
        labels:
          network: 'mainnet'
          chain_id: '138'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [network]
        target_label: network
      - source_labels: [chain_id]
        target_label: chain_id
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'besu_(blockchain_height|network_peer_count|synchronizer_block_height|transaction_pool_transactions|network_discovery_peer_count|network_peer_limit)'
        action: keep

  - job_name: 'besu-testnet'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9546']
        labels:
          network: 'testnet'
          chain_id: '2138'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [network]
        target_label: network
      - source_labels: [chain_id]
        target_label: chain_id
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'besu_(blockchain_height|network_peer_count|synchronizer_block_height)'
        action: keep

  - job_name: 'besu-devnet'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9547']
        labels:
          network: 'devnet'
          chain_id: '1337'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [network]
        target_label: network
      - source_labels: [chain_id]
        target_label: chain_id
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'besu_(blockchain_height|network_peer_count)'
        action: keep

  - job_name: 'besu-node-metrics'
    scrape_interval: 30s
    static_configs:
      - targets:
        - 'localhost:9545'  # mainnet
        - 'localhost:9546'  # testnet
        - 'localhost:9547'  # devnet
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'process_(cpu_seconds_total|resident_memory_bytes|virtual_memory_bytes|open_fds)'
        action: keep

alerting:
  alertmanagers:
    - kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: ['monitoring']
      scheme: http
      timeout: 10s
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: alertmanager
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex: "9093"
          action: keep

rule_files:
  - /etc/prometheus/rules/*.yml

storage:
  tsdb:
    retention: 15d
    retention.size: 45GB

remote_write:
  - url: ${REMOTE_WRITE_URL}
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'besu_.*'
        action: keep

recording_rules:
  groups:
    - name: besu_mainnet_rules
      interval: 1m
      rules:
        - record: besu:block_height_mainnet
          expr: besu_blockchain_height{chain_id="138"}
        - record: besu:peer_count_mainnet
          expr: besu_network_peer_count{chain_id="138"}
        - record: besu:sync_status_mainnet
          expr: besu_synchronizer_sync_status{chain_id="138"}

    - name: besu_testnet_rules
      interval: 2m
      rules:
        - record: besu:block_height_testnet
          expr: besu_blockchain_height{chain_id="2138"}
        - record: besu:peer_count_testnet
          expr: besu_network_peer_count{chain_id="2138"}
        - record: besu:sync_status_testnet
          expr: besu_synchronizer_sync_status{chain_id="2138"}

    - name: besu_devnet_rules
      interval: 5m
      rules:
        - record: besu:block_height_devnet
          expr: besu_blockchain_height{chain_id="1337"}
        - record: besu:peer_count_devnet
          expr: besu_network_peer_count{chain_id="1337"}
        - record: besu:sync_status_devnet
          expr: besu_synchronizer_sync_status{chain_id="1337"}

    - name: besu.rules
      rules:
        - alert: BesuNodeDown
          expr: up{job="besu"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Besu node is down"
            description: "Node {{ $labels.instance }} has been down for more than 5 minutes"

        - alert: BesuPeerCountLow
          expr: besu_network_peer_count < 3
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Low peer count"
            description: "Node {{ $labels.instance }} has less than 3 peers for 15 minutes"

        - alert: BesuBlockHeight
          expr: (max(besu_blockchain_height) - besu_blockchain_height) > 50
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Node falling behind"
            description: "Node {{ $labels.instance }} is more than 50 blocks behind the network"